### PR TITLE
Data model

### PR DESCRIPTION
**Pull request by chimwemwe007**
- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
- Postgres database set up.
- Build project schema.
- Create and run the necessary migration files.
- Table and column names should match the ERD diagram.
- note: photo for users table should be a link to an image
- Foreign keys should be included.
- All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Comment by chimwemwe007** [comment]
* Everything is passing but the rubocop linter is not passing on github, below is a screenshot verifying my statement.*
datamodel

**Comment by chimwemwe007** [comment]
There is one small linter error im not able to solve, kindly assist if yu can, i would greatly appreciate..

**Comment by chimwemwe007** [comment]
its showing there no linter errors but github is showing errors, below is a screenshot of the evidence.

datamlint

**Review by uwadonat — APPROVED** [review]
## Hi @chimwemwe007,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Professional readme file ✔️
- Good pull request message ✔️
appr4

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Pull request merged**
